spring:
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/my_store?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

server:
  port: 8080

aliyun:
  oss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    bucketName:

alipay:
  appId:
  appPrivateKey:
  alipayPublicKey:
  notifyUrl:
  serverUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  returnUrl: http://localhost:3000/#/allorder
