package com.nju.mystore.enums;

public enum ProductEnum {
    FOOD_DRINKS,FOOD_SNACKS, FOOD_FRESH_FOOD,
    CLOTHES_MEN, CLOTHES_WOMEN, CLOTHES_KIDS,
    ELECTRONICS,
    ENTERTAINMENT_TOYS,ENTERTAINMENT_BOOKS,ENTERTAINMENT_MUSIC,
    SPORTS_RUNNING,SPORTS_BALLS,
    LUXURY_JEWELRY,LUXURY_WATCH,
    FURNITURE_BATHS,FURNITURE_LIGHTS
}
